# Generated by Django 5.1 on 2025-05-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_article_alter_product_category_and_more'),
        ('warehouse', '0002_alter_loader_is_available_alter_loader_load_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='warehouse.zone'),
        ),
    ]
