# Generated by Django 5.1 on 2025-05-18 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryreport',
            old_name='month',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='total_amount',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts_worked', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salaryreport')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
