# Generated by Django 5.2 on 2025-05-19 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rename_month_salaryreport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
