# Generated by Django 5.2 on 2025-05-13 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('electric', 'Электрический'), ('manual', 'Ручной')], max_length=20)),
                ('load_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('refrigerator', 'Холодильник'), ('rack', 'Стеллаж')], max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.zonecategory')),
            ],
        ),
    ]
