# Generated by Django 5.1 on 2025-05-18 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='loader',
            name='load_capacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='loader',
            name='type',
            field=models.CharField(blank=True, choices=[('electric', 'Электрический'), ('manual', 'Ручной')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='capacity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='zone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.zonecategory'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='zonecategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='zonecategory',
            name='type',
            field=models.CharField(blank=True, choices=[('refrigerator', 'Холодильник'), ('rack', 'Стеллаж')], max_length=20, null=True),
        ),
    ]
