# Generated by Django 5.1 on 2025-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_loader_is_available_alter_loader_load_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loader',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
