# Generated by Django 5.2 on 2025-05-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shifts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
