# Generated by Django 5.2 on 2025-05-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_salary_customuser_shifts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='salary',
            new_name='salary_rate',
        ),
    ]
