# Generated by Django 5.1 on 2025-05-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_salary_customuser_salary_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shifts',
        ),
    ]
