# Generated by Django 5.1 on 2025-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('driver', 'Водитель'), ('customer', 'Заказчик')], max_length=20, unique=True),
        ),
    ]
