# Generated by Django 5.2 on 2025-04-25 12:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('article', models.CharField(max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('storage_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoaderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_progress', 'Cобирается'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('statement', models.JSONField()),
                ('is_aproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В обработке'), ('accepted', 'Подтверждено'), ('declined', 'Отклонено')], max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.FloatField(default=0.01)),
                ('current_load', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature_mode', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('inventory_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.inventoryreport')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.itemcategory'),
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.loadercategory')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_license', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.loader')),
                ('working_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='DecelinedWaybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.waybill')),
            ],
        ),
        migrations.CreateModel(
            name='WaybillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.item')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.waybill')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaApp.staffrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='waybill',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.zonastaff'),
        ),
        migrations.AddField(
            model_name='item',
            name='zonde_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.zone'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.zonecategory'),
        ),
    ]
