# Generated by Django 5.2 on 2025-04-25 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='_license',
            new_name='driver_license',
        ),
        migrations.AddField(
            model_name='item',
            name='load',
            field=models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='zone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ZonaApp.zonecategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='capacity',
            field=models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
