# Generated by Django 5.2 on 2025-04-25 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaApp', '0002_rename__license_driver_driver_license_item_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='load',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
