# Generated by Django 5.2 on 2025-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaApp', '0003_alter_item_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='load',
        ),
        migrations.AlterField(
            model_name='waybill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
