# Generated by Django 5.2 on 2025-04-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaApp', '0004_remove_item_load_alter_waybill_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='zonde_id',
            new_name='zone_id',
        ),
    ]
