# Generated by Django 5.2 on 2025-04-25 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaApp', '0005_rename_zonde_id_item_zone_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonastaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonastaff', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
